# Generated by Django 3.2 on 2021-05-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
