# Generated by Django 3.2 on 2021-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slalom', '0002_remove_trick_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='video1',
            field=models.CharField(default='1', max_length=250),
        ),
        migrations.AddField(
            model_name='trick',
            name='video2',
            field=models.CharField(default='2', max_length=250),
        ),
        migrations.AddField(
            model_name='trick',
            name='video3',
            field=models.CharField(default='3', max_length=250),
        ),
    ]
