# Generated by Django 3.2 on 2021-05-02 22:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slalom', '0003_auto_20210502_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='video1',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='trick',
            name='video2',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='trick',
            name='video3',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
