# Generated by Django 3.2 on 2021-05-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slalom', '0004_auto_20210502_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='link_video1',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='trick',
            name='link_video2',
            field=models.CharField(default=2, max_length=250),
        ),
        migrations.AddField(
            model_name='trick',
            name='link_video3',
            field=models.CharField(default=3, max_length=250),
        ),
    ]
